// Custom Macro definitions for use in layermaps.h. These are slightly less verbose
// than LUFA's built-in macro definitions, which improves layer map readability.
#define _MOD_LEFTCTRL                    (1 << 0)
#define _MOD_LEFTSHIFT                   (1 << 1)
#define _MOD_LEFTALT                     (1 << 2)
#define _MOD_LEFTGUI                     (1 << 3)
#define _MOD_RIGHTCTRL                   (1 << 4)
#define _MOD_RIGHTSHIFT                  (1 << 5)
#define _MOD_RIGHTALT                    (1 << 6)
#define _MOD_RIGHTGUI                    (1 << 7)

#define _ERROR_ROLLOVER                    0x01
#define _POST_FAIL                         0x02
#define _ERROR_UNDEFINED                   0x03
#define _A                                 0x04
#define _B                                 0x05
#define _C                                 0x06
#define _D                                 0x07
#define _E                                 0x08
#define _F                                 0x09
#define _G                                 0x0A
#define _H                                 0x0B
#define _I                                 0x0C
#define _J                                 0x0D
#define _K                                 0x0E
#define _L                                 0x0F
#define _M                                 0x10
#define _N                                 0x11
#define _O                                 0x12
#define _P                                 0x13
#define _Q                                 0x14
#define _R                                 0x15
#define _S                                 0x16
#define _T                                 0x17
#define _U                                 0x18
#define _V                                 0x19
#define _W                                 0x1A
#define _X                                 0x1B
#define _Y                                 0x1C
#define _Z                                 0x1D
#define _1_EXCLAMATION                     0x1E
#define _2_AT                              0x1F
#define _3_HASHMARK                        0x20
#define _4_DOLLAR                          0x21
#define _5_PERCENTAGE                      0x22
#define _6_CARET                           0x23
#define _7_AMPERSAND                       0x24
#define _8_ASTERISK                        0x25
#define _9_OPENING_PARENTHESIS             0x26
#define _0_CLOSING_PARENTHESIS             0x27
#define _ENTER                             0x28
#define _ESCAPE                            0x29
#define _BACKSPACE                         0x2A
#define _TAB                               0x2B
#define _SPACE                             0x2C
#define _MINUS_AND_UNDERSCORE              0x2D
#define _EQUAL_AND_PLUS                    0x2E
#define _OPENING_BRACKET_AND_BRACE         0x2F
#define _CLOSING_BRACKET_AND_BRACE         0x30
#define _BACKSLASH_AND_PIPE                0x31
#define _NON_US_HASHMARK_AND_TILDE         0x32
#define _SEMICOLON_AND_COLON               0x33
#define _APOSTROPHE_AND_QUOTE              0x34
#define _GRAVE_ACCENT_AND_TILDE            0x35
#define _COMMA_AND_LESS_THAN_SIGN          0x36
#define _DOT_AND_GREATER_THAN_SIGN         0x37
#define _SLASH_AND_QUESTION_MARK           0x38
#define _CAPS_LOCK                         0x39
#define _F1                                0x3A
#define _F2                                0x3B
#define _F3                                0x3C
#define _F4                                0x3D
#define _F5                                0x3E
#define _F6                                0x3F
#define _F7                                0x40
#define _F8                                0x41
#define _F9                                0x42
#define _F10                               0x43
#define _F11                               0x44
#define _F12                               0x45
#define _PRINT_SCREEN                      0x46
#define _SCROLL_LOCK                       0x47
#define _PAUSE                             0x48
#define _INSERT                            0x49
#define _HOME                              0x4A
#define _PAGE_UP                           0x4B
#define _DELETE                            0x4C
#define _END                               0x4D
#define _PAGE_DOWN                         0x4E
#define _RIGHT_ARROW                       0x4F
#define _LEFT_ARROW                        0x50
#define _DOWN_ARROW                        0x51
#define _UP_ARROW                          0x52
#define _NUM_LOCK                          0x53
#define _KEYPAD_SLASH                      0x54
#define _KEYPAD_ASTERISK                   0x55
#define _KEYPAD_MINUS                      0x56
#define _KEYPAD_PLUS                       0x57
#define _KEYPAD_ENTER                      0x58
#define _KEYPAD_1_AND_END                  0x59
#define _KEYPAD_2_AND_DOWN_ARROW           0x5A
#define _KEYPAD_3_AND_PAGE_DOWN            0x5B
#define _KEYPAD_4_AND_LEFT_ARROW           0x5C
#define _KEYPAD_5                          0x5D
#define _KEYPAD_6_AND_RIGHT_ARROW          0x5E
#define _KEYPAD_7_AND_HOME                 0x5F
#define _KEYPAD_8_AND_UP_ARROW             0x60
#define _KEYPAD_9_AND_PAGE_UP              0x61
#define _KEYPAD_0_AND_INSERT               0x62
#define _KEYPAD_DOT_AND_DELETE             0x63
#define _NON_US_BACKSLASH_AND_PIPE         0x64
#define _APPLICATION                       0x65
#define _POWER                             0x66
#define _KEYPAD_EQUAL_SIGN                 0x67
#define _F13                               0x68
#define _F14                               0x69
#define _F15                               0x6A
#define _F16                               0x6B
#define _F17                               0x6C
#define _F18                               0x6D
#define _F19                               0x6E
#define _F20                               0x6F
#define _F21                               0x70
#define _F22                               0x71
#define _F23                               0x72
#define _F24                               0x73
#define _EXECUTE                           0x74
#define _HELP                              0x75
#define _MENU                              0x76
#define _SELECT                            0x77
#define _STOP                              0x78
#define _AGAIN                             0x79
#define _UNDO                              0x7A
#define _CUT                               0x7B
#define _COPY                              0x7C
#define _PASTE                             0x7D
#define _FIND                              0x7E
#define _MUTE                              0x7F
#define _VOLUME_UP                         0x80
#define _VOLUME_DOWN                       0x81
#define _LOCKING_CAPS_LOCK                 0x82
#define _LOCKING_NUM_LOCK                  0x83
#define _LOCKING_SCROLL_LOCK               0x84
#define _KEYPAD_COMMA                      0x85
#define _KEYPAD_EQUAL_SIGN_AS400           0x86
#define _INTERNATIONAL1                    0x87
#define _INTERNATIONAL2                    0x88
#define _INTERNATIONAL3                    0x89
#define _INTERNATIONAL4                    0x8A
#define _INTERNATIONAL5                    0x8B
#define _INTERNATIONAL6                    0x8C
#define _INTERNATIONAL7                    0x8D
#define _INTERNATIONAL8                    0x8E
#define _INTERNATIONAL9                    0x8F
#define _LANG1                             0x90
#define _LANG2                             0x91
#define _LANG3                             0x92
#define _LANG4                             0x93
#define _LANG5                             0x94
#define _LANG6                             0x95
#define _LANG7                             0x96
#define _LANG8                             0x97
#define _LANG9                             0x98
#define _ALTERNATE_ERASE                   0x99
#define _SYSREQ                            0x9A
#define _CANCEL                            0x9B
#define _CLEAR                             0x9C
#define _PRIOR                             0x9D
#define _RETURN                            0x9E
#define _SEPARATOR                         0x9F
#define _OUT                               0xA0
#define _OPER                              0xA1
#define _CLEAR_AND_AGAIN                   0xA2
#define _CRSEL_AND_PROPS                   0xA3
#define _EXSEL                             0xA4
#define _KEYPAD_00                         0xB0
#define _KEYPAD_000                        0xB1
#define _THOUSANDS_SEPARATOR               0xB2
#define _DECIMAL_SEPARATOR                 0xB3
#define _CURRENCY_UNIT                     0xB4
#define _CURRENCY_SUB_UNIT                 0xB5
#define _KEYPAD_OPENING_PARENTHESIS        0xB6
#define _KEYPAD_CLOSING_PARENTHESIS        0xB7
#define _KEYPAD_OPENING_BRACE              0xB8
#define _KEYPAD_CLOSING_BRACE              0xB9
#define _KEYPAD_TAB                        0xBA
#define _KEYPAD_BACKSPACE                  0xBB
#define _KEYPAD_A                          0xBC
#define _KEYPAD_B                          0xBD
#define _KEYPAD_C                          0xBE
#define _KEYPAD_D                          0xBF
#define _KEYPAD_E                          0xC0
#define _KEYPAD_F                          0xC1
#define _KEYPAD_XOR                        0xC2
#define _KEYPAD_CARET                      0xC3
#define _KEYPAD_PERCENTAGE                 0xC4
#define _KEYPAD_LESS_THAN_SIGN             0xC5
#define _KEYPAD_GREATER_THAN_SIGN          0xC6
#define _KEYPAD_AMP                        0xC7
#define _KEYPAD_AMP_AMP                    0xC8
#define _KEYPAD_PIPE                       0xC9
#define _KEYPAD_PIPE_PIPE                  0xCA
#define _KEYPAD_COLON                      0xCB
#define _KEYPAD_HASHMARK                   0xCC
#define _KEYPAD_SPACE                      0xCD
#define _KEYPAD_AT                         0xCE
#define _KEYPAD_EXCLAMATION_SIGN           0xCF
#define _KEYPAD_MEMORY_STORE               0xD0
#define _KEYPAD_MEMORY_RECALL              0xD1
#define _KEYPAD_MEMORY_CLEAR               0xD2
#define _KEYPAD_MEMORY_ADD                 0xD3
#define _KEYPAD_MEMORY_SUBTRACT            0xD4
#define _KEYPAD_MEMORY_MULTIPLY            0xD5
#define _KEYPAD_MEMORY_DIVIDE              0xD6
#define _KEYPAD_PLUS_AND_MINUS             0xD7
#define _KEYPAD_CLEAR                      0xD8
#define _KEYPAD_CLEAR_ENTRY                0xD9
#define _KEYPAD_BINARY                     0xDA
#define _KEYPAD_OCTAL                      0xDB
#define _KEYPAD_DECIMAL                    0xDC
#define _KEYPAD_HEXADECIMAL                0xDD
#define _LEFT_CONTROL                      0xE0
#define _LEFT_SHIFT                        0xE1
#define _LEFT_ALT                          0xE2
#define _LEFT_GUI                          0xE3
#define _RIGHT_CONTROL                     0xE4
#define _RIGHT_SHIFT                       0xE5
#define _RIGHT_ALT                         0xE6
#define _RIGHT_GUI                         0xE7
#define _MEDIA_PLAY                        0xE8
#define _MEDIA_STOP                        0xE9
#define _MEDIA_PREVIOUS_TRACK              0xEA
#define _MEDIA_NEXT_TRACK                  0xEB
#define _MEDIA_EJECT                       0xEC
#define _MEDIA_VOLUME_UP                   0xED
#define _MEDIA_VOLUME_DOWN                 0xEE
#define _MEDIA_MUTE                        0xEF
#define _MEDIA_WWW                         0xF0
#define _MEDIA_BACKWARD                    0xF1
#define _MEDIA_FORWARD                     0xF2
#define _MEDIA_CANCEL                      0xF3
#define _MEDIA_SEARCH                      0xF4
#define _MEDIA_SLEEP                       0xF8
#define _MEDIA_LOCK                        0xF9
#define _MEDIA_RELOAD                      0xFA
#define _MEDIA_CALCULATOR                  0xFB
